id: validate-output
name: Validate Output
squad: qa
version: "1.0"
description: Validate any squad output against its template and Definition of Done.

trigger:
  type: event
  source: system
  condition: OS status changes to "review"

participants:
  - agent: qa-lead
    role: Validates output and approves or rejects

steps:
  - id: step-01
    name: Identify artifact type
    agent: qa-lead
    task: validate-deliverable
    input: os_record, artifact
    output: artifact_type, applicable_dod
    depends_on: []
    on_fail: abort

  - id: step-02
    name: Select applicable checklist
    agent: qa-lead
    task: validate-deliverable
    input: artifact_type
    output: selected_checklist
    depends_on: [step-01]
    on_fail: retry

  - id: step-03
    name: Run checklist validation
    agent: qa-lead
    task: validate-deliverable
    input: artifact, selected_checklist
    output: checklist_results
    depends_on: [step-02]
    on_fail: retry

  - id: step-04
    name: Check DS compliance if UI
    agent: qa-lead
    task: validate-deliverable
    input: ds-compliance checklist (if applicable)
    output: ds_compliance_result
    depends_on: [step-01]
    on_fail: skip

  - id: step-05
    name: Generate validation report
    agent: qa-lead
    task: validate-deliverable
    input: all results, qa-report-tmpl
    output: validation_report
    depends_on: [step-03, step-04]
    on_fail: retry

completion:
  condition: All required checklist items pass
  output: Validation report with pass/fail status
  notify: ops-manager, source agent

constraints:
  max_steps: 6
  timeout_minutes: 20
  retry_policy: 2
  cost_ceiling: none
