id: weekly-review
name: Weekly Review
squad: ops
version: "1.0"
description: Comprehensive weekly analysis of throughput, costs, SLA compliance, and bottlenecks.

trigger:
  type: scheduled
  source: system
  condition: Every Friday at 17:00 London time

participants:
  - agent: ops-manager
    role: Aggregates data and generates report
  - agent: ops-lead
    role: Reviews metrics and identifies improvements

steps:
  - id: step-01
    name: Aggregate weekly metrics
    agent: ops-manager
    task: generate-status-report
    input: report_type=weekly, period_start, period_end, os_records
    output: weekly_metrics
    depends_on: []
    on_fail: retry

  - id: step-02
    name: Calculate weekly costs
    agent: ops-manager
    task: calculate-daily-cost
    input: weekly aggregation
    output: weekly_cost_summary
    depends_on: []
    on_fail: retry

  - id: step-03
    name: Analyze SLA compliance
    agent: ops-manager
    task: monitor-sla
    input: weekly_os_list
    output: sla_compliance_report
    depends_on: []
    on_fail: skip

  - id: step-04
    name: Identify bottlenecks
    agent: ops-lead
    task: balance-workload
    input: active_os_list, agent_workloads
    output: bottleneck_analysis
    depends_on: [step-01]
    on_fail: skip

  - id: step-05
    name: Archive completed OS
    agent: ops-manager
    task: archive-completed
    input: completed_os_list
    output: archived_count
    depends_on: []
    on_fail: skip

  - id: step-06
    name: Run weekly review checklist
    agent: ops-lead
    task: validate-os
    input: weekly-review checklist, weekly_metrics from step-01
    output: checklist_result
    depends_on: [step-01, step-02, step-03]
    on_fail: escalate

  - id: step-07
    name: Generate weekly summary
    agent: ops-manager
    task: generate-status-report
    input: all previous outputs, weekly-summary-tmpl
    output: weekly_summary_report
    depends_on: [step-01, step-02, step-03, step-04, step-06]
    on_fail: retry

completion:
  condition: Weekly summary generated and review checklist passed
  output: Weekly summary report (md)
  notify: user

constraints:
  max_steps: 8
  timeout_minutes: 45
  retry_policy: 2
  cost_ceiling: none
