id: release-gate
name: Release Gate
squad: qa
version: "1.0"
description: Final quality gate before any production release with full validation.

trigger:
  type: manual
  source: tech-lead
  condition: Release candidate ready for final validation

participants:
  - agent: qa-lead
    role: Orchestrates validation and makes final decision
  - agent: content-reviewer
    role: Reviews content and accessibility
  - agent: process-auditor
    role: Audits security and performance

steps:
  - id: step-01
    name: Validate deliverable against DoD
    agent: qa-lead
    task: validate-deliverable
    input: release_candidate, artifact_type
    output: dod_validation
    depends_on: []
    on_fail: abort

  - id: step-02
    name: Check accessibility
    agent: content-reviewer
    task: check-accessibility
    input: release_url
    output: accessibility_report
    depends_on: []
    on_fail: retry

  - id: step-03
    name: Verify links and forms
    agent: content-reviewer
    task: verify-links-and-forms
    input: release_url
    output: link_report
    depends_on: []
    on_fail: retry

  - id: step-04
    name: Verify tracking
    agent: content-reviewer
    task: verify-tracking
    input: release_url, expected_tracking
    output: tracking_status
    depends_on: []
    on_fail: skip

  - id: step-05
    name: Audit performance
    agent: process-auditor
    task: audit-performance
    input: release_url
    output: performance_report
    depends_on: []
    on_fail: retry

  - id: step-06
    name: Audit security
    agent: process-auditor
    task: audit-security
    input: release_candidate, scope
    output: security_report
    depends_on: []
    on_fail: abort

  - id: step-07
    name: Run release readiness checklist
    agent: qa-lead
    task: validate-deliverable
    input: release-readiness checklist, all previous outputs
    output: gate_decision
    depends_on: [step-01, step-02, step-03, step-05, step-06]
    on_fail: abort

  - id: step-08
    name: Generate release notes
    agent: qa-lead
    task: review-documentation
    input: release_notes, release-notes-tmpl
    output: final_release_notes
    depends_on: [step-07]
    on_fail: retry

completion:
  condition: All blocking checks pass and release notes approved
  output: Release approval or rejection with detailed report
  notify: tech-lead, ops-lead

constraints:
  max_steps: 10
  timeout_minutes: 60
  retry_policy: 2
  cost_ceiling: none
