id: run-checklist
name: Run Checklist
squad: qa
version: "1.0"
description: Execute any checklist on demand and generate pass/fail report.

trigger:
  type: manual
  source: user
  condition: Checklist execution requested

participants:
  - agent: qa-lead
    role: Selects and executes checklist
  - agent: content-reviewer
    role: Assists with content-related items

steps:
  - id: step-01
    name: Load requested checklist
    agent: qa-lead
    task: validate-deliverable
    input: checklist_id
    output: checklist_content
    depends_on: []
    on_fail: abort

  - id: step-02
    name: Gather required inputs
    agent: qa-lead
    task: validate-deliverable
    input: checklist requirements
    output: inputs_gathered
    depends_on: [step-01]
    on_fail: retry

  - id: step-03
    name: Execute checklist items
    agent: qa-lead
    task: validate-deliverable
    input: artifact, checklist_content
    output: item_results
    depends_on: [step-02]
    on_fail: retry

  - id: step-04
    name: Calculate gate result
    agent: qa-lead
    task: validate-deliverable
    input: item_results, gate_rules
    output: gate_result
    depends_on: [step-03]
    on_fail: retry

  - id: step-05
    name: Generate checklist report
    agent: qa-lead
    task: validate-deliverable
    input: item_results, gate_result
    output: checklist_report
    depends_on: [step-04]
    on_fail: retry

completion:
  condition: All checklist items evaluated and gate decision made
  output: Checklist execution report with pass/fail
  notify: requester

constraints:
  max_steps: 6
  timeout_minutes: 30
  retry_policy: 2
  cost_ceiling: none
