id: pricing-review
name: Pricing Review
squad: finance
version: "1.0"
description: Comprehensive pricing review and update recommendation.

trigger:
  type: manual
  source: finance-lead
  condition: Quarterly review or cost structure change

participants:
  - agent: pricing-strategist
    role: Analyzes pricing and makes recommendations
  - agent: financial-analyst
    role: Provides cost and margin analysis
  - agent: finance-lead
    role: Approves pricing changes

steps:
  - id: step-01
    name: Analyze current costs
    agent: financial-analyst
    task: analyze-unit-economics
    input: cost_data
    output: cost_analysis
    depends_on: []
    on_fail: retry

  - id: step-02
    name: Review current pricing model
    agent: pricing-strategist
    task: review-pricing-model
    input: current_pricing, cost_analysis
    output: pricing_review
    depends_on: [step-01]
    on_fail: retry

  - id: step-03
    name: Run pricing change checklist
    agent: pricing-strategist
    task: review-pricing-model
    input: pricing-change checklist
    output: checklist_result
    depends_on: [step-02]
    on_fail: abort

  - id: step-04
    name: Generate pricing recommendation
    agent: pricing-strategist
    task: review-pricing-model
    input: pricing_review, pricing-model-tmpl
    output: pricing_recommendation
    depends_on: [step-03]
    on_fail: retry

  - id: step-05
    name: Approve pricing changes
    agent: finance-lead
    task: review-pricing-model
    input: pricing_recommendation
    output: approval_decision
    depends_on: [step-04]
    on_fail: abort

completion:
  condition: Pricing review complete and decision made
  output: Pricing recommendation (md)
  notify: sales-lead, user

constraints:
  max_steps: 6
  timeout_minutes: 45
  retry_policy: 2
  cost_ceiling: none
